/**
 * devtools/copy-monaco.mjs - self-host the Monaco editor under `public/vendor/monaco/` (SAAS §5.5.1). WP23.
 *
 *   node scripts/devtools/copy-monaco.mjs            # copy if monaco-editor is installed, else say so and pass
 *   node scripts/devtools/copy-monaco.mjs --require    # fail when monaco-editor is missing (WP15's own check)
 *   node scripts/devtools/copy-monaco.mjs --clean      # remove the target first
 *
 * Why a copy and not a CDN: the production CSP has no `cdn.jsdelivr.net` in `script-src`, and the Studio must keep
 * working with no third-party request at all (K-MONACO, D2 17:00). The copied tree is GIT-IGNORED - it is build
 * output, regenerated by `npm run build` - and `monaco-editor` is WP15's dependency line, not WP23's, so this
 * script must stay friendly when the package is not installed yet.
 *
 * Plain `.mjs` on purpose: it runs from `npm run build` before any TypeScript tooling is loaded.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("../..", import.meta.url)));
/** What the Code tab loads: `/vendor/monaco/vs/loader.js`, then the AMD modules beside it. */
export const MONACO_TARGET = "public/vendor/monaco";
const SOURCE_SUBDIR = join("min", "vs");

/**
 * The installed `monaco-editor` package directory, or null.
 *
 * `require.resolve("monaco-editor/package.json")` is NOT reliable: from 0.57 the package's `exports` map has a
 * catch-all `"./*": "./esm/vs/*.js"` rule, so that specifier is rewritten to `esm/vs/package.json.js` and the
 * resolve throws MODULE_NOT_FOUND even though the package is installed. Read on its own that looks like "not
 * installed", the script exits 0, and the deployed Studio silently falls back to the textarea — which is
 * exactly the one-word K-MONACO failure `docs/notes/requests/wp15-to-wp12.md` §2 asked us to avoid.
 *
 * So: walk `node_modules/monaco-editor` up from ROOT (the layout npm actually produces, including this repo's
 * shared-junction worktrees), and keep the `require.resolve` path as a fallback for any layout that hides the
 * package somewhere else. A directory counts only when it really carries `min/vs`.
 */
function monacoDir() {
  for (let dir = ROOT; ; dir = dirname(dir)) {
    const candidate = join(dir, "node_modules", "monaco-editor");
    if (existsSync(join(candidate, SOURCE_SUBDIR))) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
  }
  try {
    const require = createRequire(import.meta.url);
    return dirname(require.resolve("monaco-editor/package.json", { paths: [ROOT] }));
  } catch {
    return null;
  }
}

function main(argv) {
  const target = join(ROOT, MONACO_TARGET);
  if (argv.includes("--clean") && existsSync(target)) rmSync(target, { recursive: true, force: true });

  const source = monacoDir();
  if (source === null) {
    const message = "monaco-editor is not installed: the Code tab falls back to the plain textarea editor (CODE_EDITOR=textarea)";
    if (argv.includes("--require")) {
      process.stderr.write(`${message}\n`);
      return 1;
    }
    process.stdout.write(`${message}\n`);
    return 0;
  }

  const version = JSON.parse(readFileSync(join(source, "package.json"), "utf8")).version;
  const from = join(source, SOURCE_SUBDIR);
  if (!existsSync(from)) {
    process.stderr.write(`monaco-editor ${version} has no ${SOURCE_SUBDIR} directory at ${source}\n`);
    return 1;
  }
  mkdirSync(target, { recursive: true });
  cpSync(from, join(target, "vs"), { recursive: true });
  const loader = join(target, "vs", "loader.js");
  if (!existsSync(loader)) {
    process.stderr.write(`copied monaco-editor ${version}, but ${MONACO_TARGET}/vs/loader.js is missing\n`);
    return 1;
  }
  process.stdout.write(`copied monaco-editor ${version} to ${MONACO_TARGET}/vs (loader.js ${statSync(loader).size} bytes)\n`);
  return 0;
}

const entry = process.argv[1] ? resolve(process.argv[1]) : "";
if (entry && fileURLToPath(import.meta.url) === entry) process.exit(main(process.argv.slice(2)));
