/**
 * contracts/v3/public-api.ts - the `/api/v1` wire schemas (SAAS §14, §6.2, §6.3). WP19 freezes the NAMES at C3;
 * **ownership moves to WP22 at C3**, which fills the fields in additively (TASKS-v3 §2 rule 12).
 *
 * Conventions (§6.3): JSON only, ISO-8601 UTC timestamps, opaque ids, `?limit`+`?cursor` pagination.
 * Request bodies use the camelCase names the spec writes (`expectedRev`, `relayId`); response payloads use the
 * snake_case the spec shows on the wire. Every schema carries `.meta({ id })` so `zod-openapi` names the component.
 *
 * The response models WP22 owns the detail of are declared **loose**: a richer real response still validates, so
 * WP22 adds fields without a breaking change. The shapes §6.2/§6.3 spell out in full are exact.
 */
import { z } from "zod";

import { MAX_SOURCE_BYTES } from "./relay-code";

const V3_ERROR_CODE = z.string();

/** §6.3: `{ error: { code, message, docs_url } }`, plus `issues` (zod paths only) or `diagnostics` (§5.3). */
export const ErrorV1 = z
  .object({
    error: z.object({
      code: V3_ERROR_CODE,
      message: z.string(),
      docs_url: z.string(),
      issues: z.array(z.object({ path: z.array(z.union([z.string(), z.number()])), message: z.string() })).optional(),
      diagnostics: z.array(z.unknown()).optional(),
    }),
  })
  .meta({ id: "ErrorV1" });

/** §6.3 pagination: `{ data, next_cursor }`. The cursor is base64url of `(created_at, id)`. */
export const PageOf = <S extends z.ZodType>(schema: S) =>
  z.object({ data: z.array(schema), next_cursor: z.string().nullable() });

export const PAGE_LIMIT_DEFAULT = 20;
export const PAGE_LIMIT_MAX = 100;

export const MeV1 = z
  .object({
    org: z.looseObject({ id: z.string(), name: z.string(), plan: z.string() }),
    key: z.looseObject({ id: z.string(), scopes: z.array(z.string()) }).nullable(),
    user: z.looseObject({ id: z.string() }).nullable(),
  })
  .meta({ id: "MeV1" });

export const RelaySummaryV1 = z
  .looseObject({ id: z.string(), slug: z.string(), title: z.string(), updated_at: z.string() })
  .meta({ id: "RelaySummaryV1" });

/** The draft blueprint with secret **refs** only — a value is never echoed (§10.2). */
export const RelayDetailV1 = z
  .looseObject({ id: z.string(), slug: z.string(), title: z.string(), rev: z.number().int(), hash: z.string() })
  .meta({ id: "RelayDetailV1" });

export const RelaySourceV1 = z
  .object({
    format: z.enum(["yaml", "json"]),
    text: z.string(),
    rev: z.number().int(),
    hash: z.string(),
    stored: z.boolean(),
  })
  .meta({ id: "RelaySourceV1" });

export const VersionV1 = z
  .looseObject({ id: z.string(), version: z.number().int(), hash: z.string(), created_at: z.string() })
  .meta({ id: "VersionV1" });

export const CompiledPreviewV1 = z
  .looseObject({ greeting: z.string(), greeting_words: z.number().int(), first_update_ok: z.boolean() })
  .meta({ id: "CompiledPreviewV1" });

const SourceBodyV1 = z.object({ format: z.enum(["yaml", "json"]), text: z.string().max(MAX_SOURCE_BYTES) });

/** `POST /relays` (§6.2). */
export const CreateRelayV1 = z
  .object({
    from: z.union([
      z.object({ kind: z.literal("clone"), relayId: z.string() }),
      z.object({ kind: z.literal("blueprint"), blueprint: z.unknown() }),
      z.object({ kind: z.literal("source"), source: SourceBodyV1 }),
    ]),
  })
  .meta({ id: "CreateRelayV1" });

/** `PUT /relays/{id}/source` (§6.2); 409 answers with `{ rev, hash }`. */
export const SaveSourceV1 = z
  .object({ source: SourceBodyV1, expectedRev: z.number().int().nonnegative() })
  .meta({ id: "SaveSourceV1" });

/** `PUT /relays/{id}/draft` (§6.2); the source is regenerated by `applyEdit`. */
export const SaveDraftV1 = z
  .object({ blueprint: z.unknown(), expectedRev: z.number().int().nonnegative() })
  .meta({ id: "SaveDraftV1" });

/**
 * `POST /blueprints/validate` (§6.2): a source **or** a blueprint, ≤ 256 KiB. No DB writes.
 *
 * **WP22 obligation — the 256 KiB cap is only half-expressible here.** The `source` branch carries it
 * (`SourceBodyV1.text.max(MAX_SOURCE_BYTES)`), but the `blueprint` branch is `unknown`: there is no cheap zod
 * `.max()` for an arbitrary JSON value, and a schema-level check would in any case run *after* the body is
 * parsed. §10.4 requires the bound *before* parsing — the same reason the global compile bucket (`E_BUSY`)
 * sits in front of this route. So WP22 enforces `Content-Length`/stream length ≤ `MAX_SOURCE_BYTES` at the
 * route/transport layer for **both** branches, answering `E_VALIDATION`; this schema is the second line only.
 */
export const ValidateRequestV1 = z
  .union([z.object({ source: SourceBodyV1 }), z.object({ blueprint: z.unknown() })])
  .meta({ id: "ValidateRequestV1" });

export const ValidateResultV1 = z
  .looseObject({
    valid: z.boolean(),
    hash: z.string().nullable(),
    diagnostics: z.array(z.unknown()),
    compiled: z.looseObject({}).nullable(),
  })
  .meta({ id: "ValidateResultV1" });

export const DryRunV1 = z.looseObject({ id: z.string(), status: z.string() }).meta({ id: "DryRunV1" });

export const PublicationV1 = z.looseObject({ id: z.string(), status: z.string() }).meta({ id: "PublicationV1" });

export const RunV1 = z.looseObject({ id: z.string(), status: z.string() }).meta({ id: "RunV1" });

/** `GET /cases/{id}`; `{id}` is the run id. Fields carry evidence `{turnId, channel, startMs, endMs, quote}`. */
export const CaseV1 = z.looseObject({ id: z.string() }).meta({ id: "CaseV1" });

export const UsageV1 = z.looseObject({ org_id: z.string() }).meta({ id: "UsageV1" });

export const WebhookEndpointV1 = z
  .looseObject({ id: z.string(), url: z.string(), enabled: z.boolean() })
  .meta({ id: "WebhookEndpointV1" });

export const WebhookDeliveryV1 = z
  .looseObject({ id: z.string(), status: z.string() })
  .meta({ id: "WebhookDeliveryV1" });

/** The `Changeover-Version` response header on every `/api/v1` response (§6.3). */
export const PUBLIC_API_VERSION = "2026-09-25" as const;
