/**
 * gen-secrets.ts (`npm run secrets:init`) - fill the app's random secrets in `.env` (DESIGN §3.4).
 *
 * - For every generatable secret name that is absent or empty in `.env`, writes a random value
 *   (32 random bytes, base64url). An empty `NAME=` line is filled in place; a missing name is appended.
 * - NEVER overwrites a non-empty value, NEVER prints a value (only names), never touches other lines.
 * - External secrets (AssemblyAI, OpenAI, Polar) are listed as reminders, never generated.
 * - Writes atomically (temp file + rename).
 *
 * `LIMITS_AUTHORITY_KEY` must later be copied into the Zerops secret env of the `app` service (same value).
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { repoRoot } from "./lib/load-env";

/** Secrets we can generate locally (DESIGN §3.4 "S" rows that are ours, not a provider's). */
export const GENERATED_SECRETS = [
  "CASE_TOKEN_SECRET",
  "VISITOR_SECRET",
  "ADMIN_KEY",
  "CRON_SECRET",
  "AAI_WEBHOOK_SECRET",
  "AGENT_TOOL_SECRET",
  "LIMITS_AUTHORITY_KEY",
] as const;

/** Secrets that come from a provider dashboard (reported by name when empty; never generated). */
export const EXTERNAL_SECRETS = ["ASSEMBLYAI_API_KEY", "OPENAI_API_KEY", "POLAR_ACCESS_TOKEN", "POLAR_WEBHOOK_SECRET"] as const;

export function randomSecret(): string {
  return randomBytes(32).toString("base64url");
}

const LINE_RE = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/;

/** Value part of a `.env` line, without quotes or a trailing ` # comment`. */
function valueOf(rest: string): string {
  let v = rest.trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
  else v = v.replace(/\s+#.*$/, "").replace(/^#.*$/, "");
  return v.trim();
}

export interface FillResult {
  text: string;
  added: string[];
  filled: string[];
  kept: string[];
  externalMissing: string[];
}

/** Pure: returns the new `.env` text and the NAMES that changed. */
export function fillSecrets(original: string, gen: () => string = randomSecret): FillResult {
  const eol = original.includes("\r\n") ? "\r\n" : "\n";
  const lines = original.length ? original.split(/\r?\n/) : [];
  const seen = new Map<string, { index: number; value: string }>();
  lines.forEach((line, index) => {
    const m = LINE_RE.exec(line);
    if (m && !seen.has(m[1]!)) seen.set(m[1]!, { index, value: valueOf(m[2] ?? "") });
  });

  const added: string[] = [];
  const filled: string[] = [];
  const kept: string[] = [];
  for (const name of GENERATED_SECRETS) {
    const cur = seen.get(name);
    if (cur && cur.value !== "") kept.push(name);
    else if (cur) {
      lines[cur.index] = `${name}=${gen()}`;
      filled.push(name);
    } else added.push(name);
  }
  // Drop trailing empty lines, then append the new block.
  while (lines.length && lines[lines.length - 1] === "") lines.pop();
  if (added.length) {
    if (lines.length) lines.push("");
    lines.push("# App secrets generated by `npm run secrets:init` (DESIGN §3.4). Never commit; copy to Zerops secret env.");
    for (const name of added) lines.push(`${name}=${gen()}`);
  }
  const externalMissing = EXTERNAL_SECRETS.filter((n) => !seen.get(n)?.value);
  return { text: lines.join(eol) + eol, added, filled, kept, externalMissing };
}

function main(): number {
  const path = resolve(repoRoot(), ".env");
  const original = existsSync(path) ? readFileSync(path, "utf8") : "";
  const r = fillSecrets(original);
  if (r.added.length || r.filled.length) {
    const tmp = `${path}.secrets-init.tmp`;
    writeFileSync(tmp, r.text, { mode: 0o600 });
    renameSync(tmp, path);
  }
  console.log(`[secrets:init] ${path}`);
  console.log(`  appended: ${r.added.join(", ") || "(none)"}`);
  console.log(`  filled empty: ${r.filled.join(", ") || "(none)"}`);
  console.log(`  already set (untouched): ${r.kept.join(", ") || "(none)"}`);
  if (r.externalMissing.length) console.log(`  still empty (from provider dashboards): ${r.externalMissing.join(", ")}`);
  console.log("  values are never printed. Copy LIMITS_AUTHORITY_KEY (and the other app secrets) into Zerops secret env.");
  return 0;
}

const entry = process.argv[1] ? resolve(process.argv[1]) : "";
if (entry && fileURLToPath(import.meta.url) === entry) process.exit(main());
