"use client";
/**
 * client/studio/capabilities.ts - what this viewer may do with this relay.
 *
 * Three independent things decide it, and keeping them separate is the point:
 *
 *  - **`STUDIO_MODE=readonly`** (SAAS §15, the K-G3 fallback): a *deployment* switch. It hides Test, Publish, Try an
 *    edit and Import, and keeps Overview, Configure (read-only), Code (read-only), Preview and Download. The Studio
 *    then reads as "the blueprint behind Baton", which is exactly the fallback the kill criterion wants.
 *  - **the relay being read-only** (a gallery relay, or someone else's unlisted one): a *data* fact. Editing is out,
 *    but Test and "Clone to edit" are not - a judge must still be able to run the flagship.
 *  - **the principal's role** (SAAS §3.7): a viewer sees everything read-only; publish is admin+.
 *
 * Pure, so `tests/unit/studio/capabilities.test.ts` can assert the §7 acceptance rows directly.
 */
import "client-only";

import type { PlanId, Role } from "@/core/contracts/v3/identity";
import { PLANS } from "@/core/contracts/v3/plans";

export const STUDIO_MODES = ["full", "readonly"] as const;
export type StudioMode = (typeof STUDIO_MODES)[number];

export const CODE_EDITORS = ["monaco", "textarea"] as const;
export type CodeEditorMode = (typeof CODE_EDITORS)[number];

export interface StudioCapabilities {
  /** The Code tab and the Configure forms accept input. */
  canEdit: boolean;
  canTest: boolean;
  canPublish: boolean;
  canImport: boolean;
  canTryEdit: boolean;
  /** Download is never taken away: it is how someone gets their work out of a degraded deployment. */
  canDownload: boolean;
  /** Gallery relays: "Clone to edit" instead of an editor. */
  canClone: boolean;
}

export interface CapabilityInput {
  mode: StudioMode;
  /** `RelayDetail.readOnly`: a gallery relay or another workspace's unlisted one. */
  relayReadOnly: boolean;
  /** The principal's role in the active org; `null` in the v2 visitor world, which is an owner. */
  role?: Role | null;
}

const ROLE_CAN_EDIT = new Set<Role>(["owner", "admin", "member"]);
const ROLE_CAN_PUBLISH = new Set<Role>(["owner", "admin"]);

export function capabilitiesFor(i: CapabilityInput): StudioCapabilities {
  const readonlyDeployment = i.mode === "readonly";
  const role = i.role ?? "owner";
  const roleEdits = ROLE_CAN_EDIT.has(role);
  const canEdit = !readonlyDeployment && !i.relayReadOnly && roleEdits;
  return {
    canEdit,
    canTest: !readonlyDeployment && roleEdits,
    canPublish: !readonlyDeployment && !i.relayReadOnly && ROLE_CAN_PUBLISH.has(role),
    canImport: !readonlyDeployment && roleEdits,
    canTryEdit: !readonlyDeployment,
    canDownload: true,
    canClone: !readonlyDeployment && i.relayReadOnly && roleEdits,
  };
}

/** Parse `STUDIO_MODE`. Anything unrecognised reads as `full`, which is the v2 behaviour. */
export const studioMode = (raw: string | undefined): StudioMode => (raw?.trim() === "readonly" ? "readonly" : "full");

/** Parse `CODE_EDITOR`. Anything unrecognised reads as `monaco`; K-MONACO flips it to `textarea`. */
export const codeEditorMode = (raw: string | undefined): CodeEditorMode => (raw?.trim() === "textarea" ? "textarea" : "monaco");

/**
 * Parse the active org's plan. `null` means "no plan layer here yet", which is the v2 single-tenant world this code
 * still runs in — not "the cheapest plan", because a `guest` default would silently take HTTP actions away from a
 * deployment that has no plans at all (SAAS §5.6, §4.1).
 */
export const planId = (raw: string | null | undefined): PlanId | null => {
  const s = raw?.trim();
  return s && s in PLANS ? (s as PlanId) : null;
};

/** Everything the client shell needs that only the server can know. Passed down as props, never `NEXT_PUBLIC_*`. */
export interface StudioConfig {
  mode: StudioMode;
  editor: CodeEditorMode;
  /** `/schemas/blueprint-2.0.json`, served statically by Next and generated by WP23. */
  schemaUrl: string;
  /** Where `copy-monaco.mjs` put the AMD tree. */
  monacoVsPath: string;
  /** The active org's plan, or `null` where there is no plan layer yet. Gates "Add HTTP action" (SAAS §5.6). */
  plan: PlanId | null;
}

/** The raw env strings a server component hands down (`app/app/relays/studio-config.ts`). */
export interface StudioEnvProps {
  studioMode: string | null;
  codeEditor: string | null;
  /** WP21's `EntitlementView.plan` once billing lands; `null` until then. */
  plan?: string | null;
}

/** `/schemas/blueprint-2.0.json` is committed by WP23 and served statically from `public/`. */
export const BLUEPRINT_SCHEMA_PATH = "/schemas/blueprint-2.0.json";

/** Where `scripts/devtools/copy-monaco.mjs` puts the AMD tree, mirrored from `./monaco.ts` to keep this pure. */
export const MONACO_VS_PATH = "/vendor/monaco/vs";

export const configFrom = (env: StudioEnvProps): StudioConfig => ({
  mode: studioMode(env.studioMode ?? undefined),
  editor: codeEditorMode(env.codeEditor ?? undefined),
  schemaUrl: BLUEPRINT_SCHEMA_PATH,
  monacoVsPath: MONACO_VS_PATH,
  plan: planId(env.plan),
});
